import type { Task } from '@/types/task';

export const TASKS_MOCK: Task[] = [
  {
    id: 'task-001',
    title: 'Thiết kế lại trang chủ',
    description: 'Cập nhật hero section, thêm CTA, tối ưu mobile.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Nguyễn Văn An',
    dueDate: '2026-05-20',
    createdAt: '2026-05-08T08:30:00.000Z',
    tags: ['design', 'website'],
  },
  {
    id: 'task-002',
    title: 'Viết tài liệu API onboarding',
    description: 'Bao gồm authentication và 5 endpoint chính.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Thị Bình',
    dueDate: '2026-05-25',
    createdAt: '2026-05-08T09:15:00.000Z',
    tags: ['docs', 'api'],
  },
  {
    id: 'task-003',
    title: 'Sửa lỗi đăng nhập Google',
    description: 'Token bị reject sau khi refresh trang.',
    status: 'done',
    priority: 'high',
    assignee: 'Lê Hoàng Cường',
    dueDate: '2026-05-05',
    createdAt: '2026-05-02T10:00:00.000Z',
    tags: ['bug', 'auth'],
  },
  {
    id: 'task-004',
    title: 'Tối ưu query trang dashboard',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Phạm Thu Dung',
    dueDate: '2026-05-18',
    createdAt: '2026-05-07T14:00:00.000Z',
    tags: ['performance'],
  },
  {
    id: 'task-005',
    title: 'Họp review sprint cuối tháng',
    description: 'Chuẩn bị slide demo và bảng tiến độ.',
    status: 'todo',
    priority: 'low',
    assignee: 'Hoàng Minh Đức',
    dueDate: '2026-05-30',
    createdAt: '2026-05-09T07:00:00.000Z',
    tags: ['meeting'],
  },
  {
    id: 'task-006',
    title: 'Cập nhật thư viện React 18',
    description: 'Migration từ 17 sang 18, kiểm tra concurrent rendering.',
    status: 'done',
    priority: 'high',
    assignee: 'Vũ Thị Hà',
    dueDate: '2026-04-28',
    createdAt: '2026-04-20T11:30:00.000Z',
    tags: ['upgrade', 'frontend'],
  },
  {
    id: 'task-007',
    title: 'Viết unit test cho module thanh toán',
    status: 'todo',
    priority: 'high',
    assignee: 'Đỗ Quang Huy',
    dueDate: '2026-05-22',
    createdAt: '2026-05-06T09:00:00.000Z',
    tags: ['test', 'payment'],
  },
  {
    id: 'task-008',
    title: 'Thêm tính năng export Excel',
    description: 'Báo cáo doanh thu theo ngày.',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Bùi Thanh Lan',
    dueDate: '2026-05-17',
    createdAt: '2026-05-05T13:45:00.000Z',
    tags: ['feature', 'report'],
  },
  {
    id: 'task-009',
    title: 'Refactor component Modal dùng chung',
    status: 'todo',
    priority: 'low',
    assignee: 'Nguyễn Văn An',
    createdAt: '2026-05-09T15:00:00.000Z',
    tags: ['refactor'],
  },
  {
    id: 'task-010',
    title: 'Sửa giao diện responsive cho iPad',
    description: 'Trang danh sách sản phẩm bị tràn.',
    status: 'done',
    priority: 'medium',
    assignee: 'Trần Thị Bình',
    dueDate: '2026-05-03',
    createdAt: '2026-04-25T10:20:00.000Z',
    tags: ['bug', 'responsive'],
  },
  {
    id: 'task-011',
    title: 'Tích hợp cổng thanh toán VNPay',
    description: 'Đọc tài liệu, tạo mock test.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Lê Hoàng Cường',
    dueDate: '2026-06-05',
    createdAt: '2026-05-04T08:00:00.000Z',
    tags: ['integration', 'payment'],
  },
  {
    id: 'task-012',
    title: 'Audit accessibility (a11y)',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-06-15',
    createdAt: '2026-05-09T11:00:00.000Z',
    tags: ['a11y'],
  },
  {
    id: 'task-013',
    title: 'Tối ưu SEO trang sản phẩm',
    description: 'Thêm meta tags, structured data, sitemap.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Phạm Thu Dung',
    dueDate: '2026-05-28',
    createdAt: '2026-05-08T16:30:00.000Z',
    tags: ['seo', 'marketing'],
  },
  {
    id: 'task-014',
    title: 'Triển khai CI/CD GitHub Actions',
    status: 'done',
    priority: 'high',
    assignee: 'Hoàng Minh Đức',
    dueDate: '2026-04-30',
    createdAt: '2026-04-15T09:00:00.000Z',
    tags: ['devops', 'ci'],
  },
  {
    id: 'task-015',
    title: 'Viết hướng dẫn sử dụng cho team CSKH',
    description: 'Slide + video screencast 10 phút.',
    status: 'in_progress',
    priority: 'low',
    assignee: 'Vũ Thị Hà',
    dueDate: '2026-05-26',
    createdAt: '2026-05-05T10:30:00.000Z',
    tags: ['docs', 'training'],
  },
  {
    id: 'task-016',
    title: 'Sửa bug filter ngày trên Safari',
    status: 'todo',
    priority: 'medium',
    assignee: 'Đỗ Quang Huy',
    dueDate: '2026-05-19',
    createdAt: '2026-05-09T08:00:00.000Z',
    tags: ['bug', 'browser'],
  },
  {
    id: 'task-017',
    title: 'Thêm dark mode cho ứng dụng',
    description: 'Toggle ở header, lưu vào localStorage.',
    status: 'todo',
    priority: 'low',
    assignee: 'Bùi Thanh Lan',
    createdAt: '2026-05-09T13:00:00.000Z',
    tags: ['ui', 'feature'],
  },
  {
    id: 'task-018',
    title: 'Migration database PostgreSQL 16',
    description: 'Backup, test trên staging trước.',
    status: 'done',
    priority: 'high',
    assignee: 'Nguyễn Văn An',
    dueDate: '2026-04-20',
    createdAt: '2026-04-10T07:30:00.000Z',
    tags: ['database', 'devops'],
  },
  {
    id: 'task-019',
    title: 'Thiết kế email template chào mừng',
    status: 'in_progress',
    priority: 'low',
    assignee: 'Trần Thị Bình',
    dueDate: '2026-05-24',
    createdAt: '2026-05-07T11:00:00.000Z',
    tags: ['design', 'email'],
  },
  {
    id: 'task-020',
    title: 'Phân tích log lỗi production tuần qua',
    description: 'Báo cáo cho stakeholder ngày thứ 5.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Lê Hoàng Cường',
    dueDate: '2026-05-15',
    createdAt: '2026-05-06T14:00:00.000Z',
    tags: ['ops', 'analysis'],
  },
  {
    id: 'task-021',
    title: 'Cập nhật chính sách bảo mật',
    status: 'done',
    priority: 'medium',
    assignee: 'Phạm Thu Dung',
    dueDate: '2026-05-01',
    createdAt: '2026-04-22T09:30:00.000Z',
    tags: ['legal', 'docs'],
  },
  {
    id: 'task-022',
    title: 'Khảo sát UX với 5 khách hàng',
    description: 'Đặt lịch interview, chuẩn bị câu hỏi.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Hoàng Minh Đức',
    dueDate: '2026-06-01',
    createdAt: '2026-05-09T16:00:00.000Z',
    tags: ['research', 'ux'],
  },
];
